# This InstalledPackage resource is used for testing purposes.
# Namely it's for manual installation when tooling such as the
# tanzu CLI is not in play.
---
apiVersion: install.package.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: grafana-sample
  namespace: tanzu-extensions
spec:
  serviceAccountName: grafana-addon-sa
  packageRef:
    publicName: grafana
    versionSelection:
      constraints: "7.4.3-vmware0"
      prereleases: {}
