#@ load("/values.star", "values")
#@ if values.vsphereCPI.nsxt.podRoutingEnabled and values.vsphereCPI.nsxt.secretName != "" and values.vsphereCPI.nsxt.secretNamespace != "" and values.vsphereCPI.nsxt.username != "" and values.vsphereCPI.nsxt.password != "" :
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ values.vsphereCPI.nsxt.secretName
  namespace: #@ values.vsphereCPI.nsxt.secretNamespace
stringData:
  username: #@ values.vsphereCPI.nsxt.username
  password: #@ values.vsphereCPI.nsxt.password
type: Opaque
#@ end

#@ if values.vsphereCPI.nsxt.podRoutingEnabled and values.vsphereCPI.nsxt.clientCertData != "" and values.vsphereCPI.nsxt.clientCertKeyData != "" :
---
apiVersion: v1
kind: Secret
metadata:
  name: nsxt-tls-certificates
  namespace: kube-system
type: kubernetes.io/tls
data:
  tls.crt: #@ values.vsphereCPI.nsxt.clientCertData
  tls.key: #@ values.vsphereCPI.nsxt.clientCertKeyData
  #@ if values.vsphereCPI.nsxt.rootCAData != "" :
  tls.ca: #@ values.vsphereCPI.nsxt.rootCAData
  #@ end
#@ end
