#@data/values
#@overlay/match-child-defaults missing_ok=True

---
nodeSelector: null
deployment:
  updateStrategy: null
  rollingUpdate:
    maxUnavailable: null
    maxSurge: null
daemonset:
  updateStrategy: null
azureDiskCSIDriver:
  namespace: kube-system
