#@data/values
#@overlay/match-child-defaults missing_ok=True
---
tanzuKubernetesRelease: null
namespace: kube-system
metricsServer:
  namespace: null
  createNamespace: true
  config:
    updateStrategy: RollingUpdate
    args: [] #! Add any command args here
    probe:
      failureThreshold: 3
      periodSeconds: 10
    apiServiceInsecureTLS: true
    tolerations: [] #! user can add tolerations
