---
apiVersion: v1
kind: Namespace
metadata:
  name: tkg-system-networking   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:                       
    app: tanzu-ako-operator    
  name: ako-operator-controller-manager
  namespace: tkg-system-networking
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tanzu-ako-operator
  template:
    metadata:
      labels: 
        app: tanzu-ako-operator
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /manager
          image: projects.registry.vmware.com/tkg/ako-operator:v1.3.0_vmware.1
          name: manager
          env:
            - name: bootstrap_cluster
              value: "False"
            - name: avi_control_plane_ha_provider
              value: "False"
            - name: tkg_management_cluster_name
              value: "default-cluster"
            - name: control_plane_endpoint_port
              value: "6443"
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10
