#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:sha256", "sha256")
#@ load("/libs/constants.lib.yaml", "pinniped_supervisor_namespace", "jwt_authenticator_name", "federation_domain_name", "pinniped_supervisor_svc_name", "pinniped_cert_name", "post_deploy_job_name", "is_dex_required")
#@ load("/globals.star", "get_image_location", "globals")
#@ load("/kinds.lib.yaml", "kind_overlays")

#@ kind = kind_overlays
#@ job_metadata = overlay.subset({"metadata": {"name" : post_deploy_job_name()}})

#@ def get_id_mgmt_type():
#@   if data.values.identity_management_type:
#@     return data.values.identity_management_type
#@   end
#@   #! For backward compatibility, if not identity_management_type provided we read from dex config
#@   if data.values.dex.config.connector:
#@     return data.values.dex.config.connector
#@   end
#@   return ""
#@ end

#@ def get_hash():
#@   return sha256.sum(yaml.encode(data.values))
#@ end

#@ commands = ["/tkg-pinniped-post-deploy"]
#@ if data.values.tkg_cluster_role == "management":
#@   commands.append("--supervisor-namespace={}".format(pinniped_supervisor_namespace()))
#@   commands.append("--supervisor-svc-name={}".format(pinniped_supervisor_svc_name()))
#@   commands.append("--federationdomain-name={}".format(federation_domain_name()))
#@   commands.append("--jwtauthenticator-name={}".format(jwt_authenticator_name()))
#@   commands.append("--supervisor-cert-name={}".format(pinniped_cert_name()))
#@   commands.append("--custom-tls-secret={}".format(data.values.custom_tls_secret))
#@   if is_dex_required():
#@     commands.append("--dex-namespace={}".format(data.values.dex.namespace))
#@     commands.append("--dex-svc-name={}".format(data.values.dex.service.name))
#@     commands.append("--dex-cert-name={}-cert".format(data.values.dex.app))
#@     commands.append("--dex-configmap-name={}".format(data.values.dex.app))
#@   end
#@ else:
#@   commands.append("--jwtauthenticator-name={}".format(jwt_authenticator_name()))
#@   commands.append("--supervisor-svc-endpoint={}".format(data.values.pinniped.supervisor_svc_endpoint))
#@   commands.append("--supervisor-ca-bundle-data={}".format(data.values.pinniped.supervisor_ca_bundle_data))
#@ end
#@ commands.append("--is-dex-required={}".format(is_dex_required()))
#@ commands.append("--concierge-is-cluster-scoped=true")

#@overlay/match by=overlay.and_op(kind.job, job_metadata)
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/update-strategy: always-replace
    pinniped-addon-template/hash: #@ get_hash()
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      containers:
        #@overlay/match by="name"
        - name: pinniped-post-deploy
          #@overlay/replace
          command: #@ commands
