#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@ def labels():
app: tanzu-ako-operator
#@ end

#@overlay/match by=overlay.subset({"kind": "Namespace", "metadata": {"name": "tkg-system-networking"}})
---
#@overlay/replace
apiVersion: v1
kind: Namespace
metadata:
  name: #@ values.akoOperator.namespace

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "ako-operator-controller-manager"}})
---
#@overlay/replace
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels()
  name: ako-operator-controller-manager
  namespace: #@ values.akoOperator.namespace
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
        #@overlay/match by="name"
        #@overlay/replace
        - args:
            - --metrics-addr=:8080
          command:
            - /manager
          image: projects-stg.registry.vmware.com/tkg/ako-operator:v1.7.0_vmware.1
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          env:
            - name: bootstrap_cluster
              value: "False"
            - name: avi_control_plane_ha_provider
              value: #@ "{}".format(values.akoOperator.config.avi_control_plane_ha_provider)
            - name: control_plane_endpoint_port
              value: #@ "{}".format(values.akoOperator.config.avi_control_plane_endpoint_port)
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
