#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ClusterRole"}), expects=1
---
rules:
#@overlay/append
- apiGroups: ["projectcontour.io"]
  resources: ["httpproxies"]
  verbs: ["get", "watch", "list"]
#@overlay/append
- apiGroups: ['networking.k8s.io']
  resources: ['ingresses']
  verbs: ['get', 'watch', 'list']
#@overlay/append
- apiGroups: ['']
  resources: ['nodes']
  verbs: ['watch']
  