#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "kube-multus-ds-amd64"}})
#@overlay/match-child-defaults missing_ok=True
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "kube-multus"})
      - 
        #@overlay/remove
        args:

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "kube-multus-ds-amd64"}})
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  namespace: #@ data.values.namespace
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "kube-multus"})
      - 
        image: #@ "{}/{}:{}".format(data.values.image.repository, data.values.image.name, data.values.image.tag)
        args: #@ data.values.daemonset.args

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "kube-multus-ds-ppc64le"}})
#@overlay/remove
---

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "kube-multus-ds-s390x"}})
#@overlay/remove
---

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "kube-multus-ds-arm64v8"}})
#@overlay/remove
---
