#@data/values
#@overlay/match-child-defaults missing_ok=True

---
vsphereCPI:
  tlsThumbprint: ""
  server: null
  datacenter: null
  username: null
  password: null
  region: null
  zone: null
  insecureFlag: False
  ipFamily: null
  vmInternalNetwork: null
  vmExternalNetwork: null
  cloudProviderExtraArgs:
    tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  nsxt:
    podRoutingEnabled: false
    routes:
      routerPath: ""
      clusterCidr: ""
    username: ""
    password: ""
    host: null
    insecureFlag: "false"
    remoteAuth: "false"
    vmcAccessToken: ""
    vmcAuthHost: ""
    clientCertKeyData: ""
    clientCertData: ""
    rootCAData: ""
    secretName: "cloud-provider-vsphere-nsxt-credentials"
    secretNamespace: "kube-system"
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
