apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/upstream
  contents:
  - path: alertmanager
    manual: {}
  - path: prometheus
    manual: {}
