---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "harbor-ingress"
  labels:
    app: "harbor"
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  namespace: tanzu-system-registry
spec:
  tls:
    - secretName: harbor-tls
      hosts:
        - core.harbor.domain
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: harbor-portal
                port:
                  number: 443
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: harbor-core
                port:
                  number: 443
          - path: /service
            pathType: Prefix
            backend:
              service:
                name: harbor-core
                port:
                  number: 443
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: harbor-core
                port:
                  number: 443
          - path: /chartrepo
            pathType: Prefix
            backend:
              service:
                name: harbor-core
                port:
                  number: 443
          - path: /c
            pathType: Prefix
            backend:
              service:
                name: harbor-core
                port:
                  number: 443
      host: core.harbor.domain
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "harbor-ingress-notary"
  labels:
    app: "harbor"
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  namespace: tanzu-system-registry
spec:
  tls:
    - secretName: harbor-tls
      hosts:
        - notary.harbor.domain
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: harbor-notary-server
                port:
                  number: 4443
      host: notary.harbor.domain
