apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-file-system-volume-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: oci-file-system-volume-provisioner
      tier: control-plane
  template:
    metadata:
      labels:
        component: oci-file-system-volume-provisioner
        tier: control-plane
    spec:
      serviceAccountName: oci-volume-provisioner
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: config
          secret:
            secretName: oci-volume-provisioner
      containers:
        - name: oci-volume-provisioner
          image: ghcr.io/oracle/cloud-provider-oci:v1.22.1
          command: ["/usr/local/bin/oci-volume-provisioner"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PROVISIONER_TYPE
              value: oracle.com/oci-fss
          volumeMounts:
            - name: config
              mountPath: /etc/oci/
              readOnly: true
