#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespace: kapp-controller
kappController:
  namespace: null
  createNamespace: true
  globalNamespace: kapp-controller-packaging-global
  deployment:
    hostNetwork: null
    priorityClassName: null
    concurrency: 2
    tolerations: []
    apiPort: 10350
  config:
    caCerts: ""
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
    dangerousSkipTLSVerify: ""
