#! schema.yml

#@data/values-schema
#@schema/desc "OpenAPIv3 Schema for secretgen-controller"
---
#@schema/desc "Configuration for secretgen-controller"
secretgenController:
  #@schema/desc "The namespace in which to deploy secretgen-controller"
  namespace: secretgen-controller
  #@schema/desc "Whether to create namespace specified for secretgen-controller"
  createNamespace: true
