#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "local-path-provisioner"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.map_key("name")
      - name: local-path-provisioner
        #@overlay/replace
        image: #@ data.values.image
