#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cloud-provider-vsphere-credentials"}})
#@yaml/text-templated-strings
---
#@overlay/replace
stringData:
  (@=values.vsphereCPI.server@).username: (@=values.vsphereCPI.username@)
  (@=values.vsphereCPI.server@).password: (@=values.vsphereCPI.password@)
