#@data/values
#@overlay/match-child-defaults missing_ok=True
---
imageInfo:
  imageRepository: projects-stg.registry.vmware.com/tkg
  imagePullPolicy: IfNotPresent
  images:
    tkgPinnipedPostDeployImage:
      imagePath: tkg-pinniped-post-deploy
      tag: v0.4.1_vmware.1
    pinnipedImage:
      imagePath: pinniped
      tag: v0.4.1_vmware.1
    dexImage:
      imagePath: dex
      tag: v2.27.0_vmware.1
infrastructure_provider: null
tkg_cluster_role: null
custom_cluster_issuer: "" #! provide if user wants to use a custom ClusterIssuer for both Pinniped and Dex certificates
custom_tls_secret: "" #! provide if user wants to use a custom TLS secret for both Pinniped and Dex, will override the ClusterIssuer above if specified, user should create secret with the smae name in both "tanzu-system-auth" and "pinniped-supervisor" namespaces.
http_proxy: ""
https_proxy: ""
no_proxy: ""
identity_management_type: null
pinniped:
  cert_duration: 2160h
  cert_renew_before: 360h
  supervisor_svc_endpoint: "https://0.0.0.0:31234" #! Do not change. Will be updated by post-deployment job. This is used to configure jwtAuthenticator
  supervisor_ca_bundle_data: "ca_bundle_data_of_pinniped_supervisor_svc" #! Do not change. Will be updated by post-deployment job. This is used to configure jwtAuthenticator to communicate with supervisor svc
  supervisor_svc_external_ip: "0.0.0.0" #! provide if the node IP or LB IP of Pinniped supervisor service is known, otherwise leave it empty. e.g. 10.165.123.84
  supervisor_svc_external_dns: null #! provide if the LB DNS of Pinniped supervisor service is known, otherwise leave it empty. e.g pinniped-svc.us-west-2a.com
  upstream_oidc_client_id: "" #! the client secret used to talk to Dex
  upstream_oidc_client_secret: "" #! the client secret used to talk to Dex
  upstream_oidc_issuer_url: "https://0.0.0.0:30167" #! the upstream oidc issuer url. It should be pointed to Dex service, since Dex is deployed as the upstream of Pinniped. e.g https://endpoint-points-to-dex:5443
  upstream_oidc_tls_ca_data: "ca_bundle_data_of_dex_svc" #! this tls ca data is used to communicate with upstream_oidc_issuer_url
dex:
  app: dex
  create_namespace: true
  namespace: tanzu-system-auth
  organization: vmware
  commonname: tkg-dex
  config:
    frontend:
      theme: tkg
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    expiry:  #! these will need to be adjusted with future updated to Pinniped
      signingKeys: 90m
      idTokens: 5m
      authRequests: 90m
      deviceRequests: 5m
    logger:
      level: info
      format: json
    #! staticClients is skipped in values.yaml but required to be provided in values overlay
    #! connector is not dex officially supported config variable, it was originally added to let ytt have some knowledge
    #! about connector type in order to overlay the template properly. Have it assigned with null to make sure default
    #! value could also be picked up by ytt if no data value overrides it.
    connector: null
    issuerPort: "30167" #! requred only for MGMT_CLUSTER_VIP if provider is vsphere. Default is "30167"
    oidc:
      CLIENT_ID: null #! required if oidc enabled
      CLIENT_SECRET: null #! required if oidc enabled
      issuer: null #! <OIDC_IDP_URL> is required if oidc enabled
      clientID: $OIDC_CLIENT_ID  #! do not change this
      clientSecret: $OIDC_CLIENT_SECRET #! do not change this
      basicAuthUnsupported: null
      #! hostedDomains is skipped in values.yaml but required to be provided in values overlay
      #! scopes is skipped in values.yaml but required to be provided in values overlay
      insecureEnableGroups: true
      insecureSkipEmailVerified: false
      getUserInfo: null
      userIDKey: null
      userNameKey: null
      claimMapping:
        email: email
        email_verified: email_verified
    ldap:
      host: null #! <LDAP_HOST> is required if ldap enabed
      insecureNoSSL: false
      startTLS: null
      rootCA: null #! <rootCA> or <rootCAData> if required when LDAP host is using self signed certificate. Path to the CA file
      rootCAData: null #! <rootCA> or <rootCAData> if required when LDAP host is using self signed certificate. Actual CA bundle
      bindDN: null #! <bindDN> is required when host doesn't support anonymous authentication
      BIND_PW_ENV_VAR: null #! <BIND_PW_ENV_VAR> is required when host doesn't support anonymous authentication
      usernamePrompt: LDAP Username
      insecureSkipVerify: False
      userSearch:
        baseDN: null #! required if ldap userSearch enabled
        filter: "(objectClass=posixAccount)"
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: givenName
        scope: sub
      groupSearch:
        baseDN: null  #! required if ldap groupSearch enabled
        filter: "(objectClass=posixGroup)"
        nameAttr: cn
        scope: sub
        #! userMatchers section is skipped in values.yaml but required to be provided in values overlay
    oauth2:
      skipApprovalScreen: true
    storage:
     type: kubernetes
     config:
       inCluster: true     
    enablePasswordDB: false
  service:
    name: dexsvc
    type: null
    annotations: {}
  deployment:
    replicas: 1
  certificate: 
    duration: 2160h
    renewBefore: 360h
  #! dns section is skipped in values.yaml but required to be provided in values overlay
