#@data/values
#@overlay/match-child-defaults missing_ok=True

---
infraProvider: vsphere
nodeSelector: null
deployment:
  updateStrategy: null
  rollingUpdate:
    maxUnavailable: null
    maxSurge: null
daemonset:
  updateStrategy: null

antrea:
  config:
    egress:
      exceptCIDRs: []
    nodePortLocal:
      enabled: true
      portRange: 61000-62000
    antreaProxy:
      proxyAll: false
      nodePortAddresses: []
      skipServices: []
      proxyLoadBalancerIPs: false
    flowExporter:
      collectorAddress: "flow-aggregator.flow-aggregator.svc:4739:tls"
      pollInterval: "5s"
      activeFlowTimeout: "30s"
      idleFlowTimeout: "15s"
    kubeAPIServerOverride: null
    transportInterface: null
    transportInterfaceCIDRs: []
    tunnelType: geneve
    trafficEncryptionMode: none
    wireGuard:
      port: 51820
    serviceCIDR: 10.96.0.0/12
    serviceCIDRv6: null
    enableUsageReporting: false
    trafficEncapMode: encap
    noSNAT: false
    disableUdpTunnelOffload: false
    #! Setting defaultMTU to null since antrea-agent will discover the MTU of the Node's primary interface and
    #! also adjust MTU to accommodate for tunnel encapsulation overhead.
    defaultMTU: null
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
    enableBridgingMode: false
    disableTXChecksumOffload: false
    dnsServerOverride: null
    multicastInterfaces: []
    multicast:
      igmpQueryInterval: "125s"
    ipsec:
      authenticationMode: "psk"
    ipsecCSRSigner:
      autoApprove: true
      selfSignedCA: true
    multicluster:
      enable: false
      namespace: null
    featureGates:
      AntreaProxy: true
      EndpointSlice: false
      AntreaTraceflow: true
      NodePortLocal: true
      AntreaPolicy: true
      FlowExporter: false
      NetworkPolicyStats: false
      Egress: true
      AntreaIPAM: false
      ServiceExternalIP: false
      Multicast: false
      Multicluster: false
      SecondaryNetwork: false
      TrafficControl: false
      IPsecCertAuth: false
      NodeIPAM: false
