name: Check shell

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "**.sh"
      - "hack/check-shell.sh"

jobs:
  checkshell:
    name: Check shell
    runs-on: ubuntu-latest
    steps:
      - name: Config credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CHECKS_ACCESS_TOKEN }}
        run: |
          git config --global url."https://git:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run shellcheck
        run: |
          make shellcheck
