name: Check - mdlint

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "**.md"
      - "hack/check/check-mdlint.sh"

jobs:
  checkmdlint:
    name: Check mdlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run mdlint
        run: |
          make mdlint
