name: Check - shell

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "**/Makefile"
      - "**.sh"
      - "hack/check/check-shell.sh"

jobs:
  checkshell:
    name: Check shell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run shellcheck
        run: |
          make shellcheck
