name: Package - Copy Readme to Docs
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - addons/packages/**/*/[rR][eE][aA][dD][mM][eE].md
      - addons/repos/main.yaml
jobs:
  copy-to-docs:
    name: Copy to Docs
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'vmware-tanzu/community-edition'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
        id: go
      - name: Config credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGING_ACCESS_TOKEN }}
        run: |
          git config --global pull.rebase true
          git config --global url."https://git:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Copy Package Readme Files
        run: |
          cd hack/workflows/packages && go run copy-package-readmes-to-docs.go
      - name: GitHub Actions to Create and Merge Pull Request
        env:
          GH_PACKAGING_ACCESS_TOKEN: ${{ secrets.GH_PACKAGING_ACCESS_TOKEN }}
        run: |
          hack/workflows/packages/update-package-readmes.sh
