name: Push Extensions
on:
  push:
    branches-ignore:
      # disable all branches
      - '**'
    tags-ignore:
      # disable all tags
      - '**'
    paths:
      - 'extensions/**'
jobs:
  push-extensions:
    name: Push Extensions
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Push
      run: make push-extensions
