name: Release - Homebrew Package

on:
  release:
    types:
      - released

jobs:
  update-homebrew-package:
    name: Update Homebrew Package
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'vmware-tanzu/community-edition'
    runs-on: ubuntu-latest
    steps:
      - name: Config credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        run: |
          git config --global pull.rebase true
          git config --global url."https://git:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Check out code
        uses: actions/checkout@v3

      - name: Update Homebrew Package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        shell: bash
        run: |
          GITHUB_REF="${{ github.ref }}"
          version=${GITHUB_REF/refs\/tags\//}
          ./hack/homebrew/update-homebrew-package.sh ${version}
